### ISSUE TITLE
App breaks when a forecast isn't produced for a location

### ISSUE THREAD

**Issue by stephenturner** [signaturescience/fiphde#131]
TSENS didn't produce a forecast for Alabama on 2022-10-31. CREG did. 

![image](https://user-images.githubusercontent.com/460076/199003010-15e5d9e2-ab9e-47c5-bce5-c0a778568c4b.png)

When unchecking CREG to display TSENS only, app results with an error message:

![image](https://user-images.githubusercontent.com/460076/199003135-193c773d-51e2-486d-8398-4eaa3da3e0ab.png)

Unchecking the offending state will let the app continue to display results, but this behavior should be investigated.

**Comment by vpnagraj** [comment]
candidate fix for this issue in PR to dev: 

https://github.com/signaturescience/fiphde/pull/133

if you want to try this yourself:

1. download the explorer forecast csv files for 2022-10-31
2. name each file as {file-prefix}.candidate.csv
3. move the TSENS and CREG csv files to their respective dirs in the `submission/` relative to this repo root
4. run the code below

```
library(fiphde)

## NOTE: submission_dir and app_dir may need to be reset to run locally
submission_dir <- here::here("submission")

prepped_hosp <-
  get_hdgov_hosp(limitcols = TRUE) %>%
  prep_hdgov_hosp(statesonly=TRUE, min_per_week = 0, remove_incomplete = TRUE) %>%
  dplyr::filter(abbreviation != "DC")

fiphde_launcher(.data = prepped_hosp,
                submission_dir = submission_dir,
                host = "0.0.0.0",
                launch.browser = TRUE,
                port = 80)
```

i think that does it?

if all looks good to you feel free to merge PR to dev, then we can prep a minor release using dev to main PR
