### ISSUE TITLE
refactor repo to remove to submission directory

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/fiphde#145]
we should simplifying the overall maintenance and structure of the repository by tracking the submission.R and example "submission" materials elsewhere

**Comment by stephenturner** [comment]
PR in #147 to remove submission dir from fiphde. Moved to new repo, https://github.com/signaturescience/fiphde-sub (currently private). Need to coordinate merge to main with updating AWS automation to pull directly from https://raw.githubusercontent.com/signaturescience/fiphde-sub/main/submission.R on main.
