### ISSUE TITLE
drop weighted_interval_score function?

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/fiphde#155]
should we continue to export the `weighted_interval_score()` function? 

it is implemented in https://cmu-delphi.github.io/covidcast/evalcastR/index.html

what do we add by re-implementing here?

**Comment by vpnagraj** [comment]
note if were to remove we could also jettison `score_func_param_checker()`

**Comment by stephenturner** [comment]
I believe our reasoning here was that evalcastR has [many extra dependencies](https://github.com/cmu-delphi/covidcast/blob/main/R-packages/evalcast/DESCRIPTION), the package itself is a subdirectory of a repo, which made importing difficult (I think this is resolved now with newer versions of R/devtools), and we only needed this relatively simple function. Maybe we don't export it, but don't remove it from the package - _we_ might still use it.

**Comment by stephenturner** [comment]
hey @chulmelowe before we remove this, are you able to able to install evalcastR either on your personal machine or on Darwin?

**Comment by stephenturner** [comment]
closed via #164
