### ISSUE TITLE
make model names in ts_fit_forecast more flexible

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/fiphde#157]
the list of models names passed to `ts_fit_forecast()` is very strict when it comes to the named elements passed to the "models" argument. it is case sensitive (if you pass in a list with an element named "ARIMA" instead of "arima" it will assume ARIMA is `NULL`) and doesnt allow you to pass in different "flavors" of models (e.g., a list with "arima_unrestricted" and "arima_restricted" side-by-side).

is there a way we can make the handling of model names more flexible?

**Comment by stephenturner** [comment]
Made case-insensitive in b0a1947a62229b6dd2de52dbb40dcb57285a5c58 coming in on PR #170

**Comment by stephenturner** [comment]
closed in #170
