### ISSUE TITLE
fix fallback argument for state_replace_ili_nowcast_all

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/fiphde#159]
the "fallback" method for ILI nowcast is what we refer to in docs as a "pseudo nowcast" where we take average of 4 most recent observed ILI values and use that as "nowcast":

https://github.com/signaturescience/fiphde/blob/main/R/utils.R#L34

however, when implemented in `state_replace_ili_nowcast_all()` for a state that has *almost entirely missing values* (like FL) ... this will pseudo nowcast will not return a number.

**Comment by vpnagraj** [comment]
lets remove `state_replace_ili_nowcast_all()` altogether.

**Comment by stephenturner** [comment]
related to #161

**Comment by vpnagraj** [comment]
now that we have the `ilinearby` object archived in pkg sysdata (see #165 ) lets go ahead and remove `state_replace_ili_nowcast_all()`

**Comment by stephenturner** [comment]
For sure. We'll want to simultaneously update our submission script (https://github.com/signaturescience/fiphde-sub, public soon / with 1.0.0 release).

**Comment by stephenturner** [comment]
Submission script updated in https://github.com/signaturescience/fiphde-sub/commit/d14cf2e3f26f6d579103d056d8283a54839db418

**Comment by stephenturner** [comment]
closed via #169
