### ISSUE TITLE
fiphde explorer app "working" signal

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/fiphde#175]
some of the plotting and data retrieval functions in the explorer app take a bit of time. 

can we add a progressing spinner to indicate "working" status. something from `shinycssloaders` ? or another approach?

@dwill023 please have a look at this. work on a new branch and when you're ready for a review open a PR to `main`. if you have thoughts/questions/dialogue in the meantime lets use the thread in this issue.

a few things to orient you up front:

- the app code is distributed inside the `inst/` dir (https://github.com/signaturescience/fiphde/blob/main/inst/app/app.R)
- if we can minimize dependencies that would be great (i.e., add the functionality from existing packages needed https://github.com/signaturescience/fiphde/blob/main/inst/app/app.R#L1-L10) ... not sure that's possible to do, but just want to point out.
- the docs on the `fiphde_launcher()` function will show you how to run the app (https://signaturescience.github.io/fiphde/reference/fiphde_launcher.html)

**Comment by dwill023** [comment]
@vpnagraj  Ok I think I've created a branch shiny_app, push my changes and created a pull request correctly but please check for me.

**Comment by vpnagraj** [comment]
just tested and this looks good. there is one more thing to do ...

since the app is delivered as part of the R package we need to track the new dependency (`waiter`).

strictly speaking a user of the `fiphde` R package can use most of the functionality *without* this dependency. so this is actually a rare use-case for adding a dependency to "Suggests" (instead of "Imports").

for an example of how we do that for other packages *just* used in the shiny app:

https://github.com/signaturescience/fiphde/blob/main/DESCRIPTION#L54

for a little more on the Suggests convention:

https://r-pkgs.org/dependencies-in-practice.html#sec-dependencies-in-suggests

**Comment by vpnagraj** [comment]
done in #178
