### ISSUE TITLE
"anomaly" smoothing using coverage

### ISSUE THREAD

**Issue by stephenturner** [signaturescience/fiphde#19]
The ground truth "COVID-19 Reported Patient Impact and Hospital Capacity by State Timeseries" data (https://healthdata.gov/Hospital/COVID-19-Reported-Patient-Impact-and-Hospital-Capa/g62h-syeh) reports several "coverage" metrics. These correspond to the Number of hospitals reporting <whatever metric> in that state. We should pay particular attention to the coverage we see, and potentially consider how we might "smooth out" days or weeks of low coverage data that might occur over events such as holidays, weather/disasters, etc.

For example, look at Texas and Virginia. The normal wiggle you see is weekday/weekend reporting. This should get smoothed out when summing by week. But what about large swings like in late 2020 in TX, or weird systematic shifts like what's seen in TS in early 2021 where coverage drops substantially?

![image](https://user-images.githubusercontent.com/460076/146821534-d74b16f5-7971-4799-8165-ae9c6820caa9.png)

**Comment by vpnagraj** [comment]
returning to this issue and seeing that it is out of scope for fiphde. 

closing.
